# Generated by Django 2.0 on 2020-05-22 15:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('Foto', models.ImageField(default=None, upload_to='profile', verbose_name='Foto')),
                ('Login', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('Matricula', models.CharField(max_length=128, verbose_name='Matricula')),
                ('Situacao', models.BooleanField(default=True, verbose_name='Ativo')),
                ('CPF', models.CharField(max_length=20, verbose_name='CPF')),
                ('RG', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('Rua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('N', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('CEP', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('Facebook', models.CharField(blank=True, max_length=120, null=True, verbose_name='Facebook link')),
                ('Instagram', models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram link')),
                ('LinkedIn', models.CharField(blank=True, max_length=120, null=True, verbose_name='LinkedIn link')),
                ('Data_de_Nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('Data_de_Admissão', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('Data_de_Demissão', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('Funcao', models.CharField(choices=[('PROP', 'Proprietario'), ('PRE', 'Presidencia'), ('MAR', 'Marketing'), ('QUA', 'Qualidade'), ('ADM', 'Adm/Fin'), ('PRO', 'Projetos'), ('RH', 'Recursos Humanos')], max_length=4, verbose_name='Função')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True, verbose_name='Último login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da Equipe')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPublicacao', models.DateField(blank=True, null=True, verbose_name='data')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome')),
                ('cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bairro')),
                ('rua', models.CharField(blank=True, max_length=80, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero')),
                ('cep', models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF/CNPJ')),
                ('contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'processos',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despesa', models.CharField(choices=[('DOM', 'Domínio'), ('SN', 'Simples-Nacional'), ('HOSP', 'Hospedagem'), ('ISS', 'ISS'), ('MUL', 'Multa'), ('OUT', 'Outros')], max_length=4, verbose_name='Despesa')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Ouvidoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateField(blank=True, null=True, verbose_name='Entrega')),
                ('status', models.IntegerField(choices=[(0, 'Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Resolvido')], verbose_name='Status')),
                ('responsaveis', models.ManyToManyField(blank=True, null=True, related_name='responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('Entrada', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Entrada')),
                ('valorParcela', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da Parcela')),
                ('Pagamento', models.BooleanField(default=True, verbose_name='Pagamento Efetuado')),
                ('parcelamento', models.IntegerField(choices=[(1, '01-A VISTA'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], max_length=4, verbose_name='Parcelado')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Rerceitas',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataReuniao', models.DateField(blank=True, null=True, verbose_name='Data da Reunião')),
                ('tipoReuniao', models.CharField(choices=[('GER', 'GERAL'), ('DIR', 'DIRETORIA'), ('PRO', 'PROJETOS')], max_length=4, verbose_name='Reunião')),
                ('descricaoReuniao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ausencia', models.ManyToManyField(blank=True, null=True, related_name='ausencia', to=settings.AUTH_USER_MODEL)),
                ('presenca', models.ManyToManyField(blank=True, null=True, related_name='presenca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeServico', models.CharField(choices=[('SPA', 'Single Page Application'), ('PWA', 'Progressive Web Application'), ('WS', 'WebSite'), ('SW', 'Sistema Web'), ('IV', 'Identidade Visual')], max_length=4, verbose_name='Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('Desconto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desconto')),
                ('parcelamento', models.IntegerField(choices=[(1, '01-A VISTA'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], max_length=4, verbose_name='Parcelado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='processos.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='Servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='processos.Servico'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicos', to='processos.Servico'),
        ),
        migrations.AddField(
            model_name='ata',
            name='Reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reuniao', to='processos.Reuniao'),
        ),
    ]
