# Generated by Django 2.0 on 2020-05-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('Desconto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desconto')),
                ('Pagamento', models.IntegerField(blank=True, null=True, verbose_name='Pagamento')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='processos.Cliente')),
                ('Servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='processos.Servico')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Rerceitas',
            },
        ),
    ]
