# Generated by Django 2.0 on 2020-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Facebook',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Instagram',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram link'),
        ),
    ]
