# Generated by Django 2.0 on 2020-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200505_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='LinkedIn',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='LinkedIn link'),
        ),
    ]
