# Generated by Django 2.0 on 2020-05-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_balanco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='Entrada',
        ),
    ]
