# Generated by Django 2.0 on 2020-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='Pagamento',
            field=models.IntegerField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default=1, max_length=4, verbose_name='Pagamento'),
            preserve_default=False,
        ),
    ]
