# Generated by Django 2.0 on 2020-05-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_usuario_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('status', models.CharField(choices=[(0, 'Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Resolvido')], max_length=4, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeServico', models.CharField(choices=[('SPA', 'Single Page Application'), ('PWA', 'Progressive Web Application'), ('WS', 'WebSite'), ('SW', 'Sistema Web'), ('IV', 'Identidade Visual')], max_length=4, verbose_name='Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
        ),
        migrations.AlterField(
            model_name='despesas',
            name='despesa',
            field=models.CharField(choices=[('ICMS', 'ICMS'), ('SN', 'Simples-Nacional'), ('GAS', 'Gasolina'), ('SER', 'Serviços'), ('INSS', 'INSS')], max_length=4, verbose_name='Despesa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicos', to='processos.Servico'),
        ),
    ]
