# Generated by Django 2.0 on 2020-05-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20200506_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='Cliente',
        ),
    ]
