# Generated by Django 2.0 on 2020-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_remove_receita_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='Pagamento',
            field=models.BooleanField(default=True, verbose_name='Pagamento Efetuado'),
        ),
    ]
