# Generated by Django 2.0 on 2020-05-05 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20200505_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datareuniao', models.DateField(blank=True, null=True, verbose_name='Data da reuniao')),
                ('ausencia', models.ManyToManyField(blank=True, null=True, related_name='ausencia', to=settings.AUTH_USER_MODEL)),
                ('presenca', models.ManyToManyField(blank=True, null=True, related_name='presenca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
