# Generated by Django 2.0 on 2020-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='tipoReuniao',
            field=models.CharField(choices=[('GER', 'GERAL'), ('DIR', 'DIRETORIA')], default=1, max_length=4, verbose_name='Reuniao'),
            preserve_default=False,
        ),
    ]
