# Generated by Django 2.0 on 2020-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_despesas_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='despesa',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Despesa'),
        ),
    ]
