# Generated by Django 2.0 on 2020-05-06 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_auto_20200506_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
