# Generated by Django 2.0 on 2020-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_auto_20200522_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='despesa',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Despesa'),
        ),
    ]
