# Generated by Django 2.0 on 2020-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_projeto_responsaveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='Pagamento',
            new_name='Parcela',
        ),
        migrations.AddField(
            model_name='receita',
            name='Valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
