# Generated by Django 2.0 on 2020-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_reuniao_tiporeuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nomeServico',
            field=models.CharField(choices=[('SPA', 'Single Page Application'), ('PWA', 'Progressive Web Application'), ('WS', 'WebSite'), ('SW', 'Sistema Web'), ('IV', 'Identidade Visual')], max_length=4, verbose_name='Serviço'),
        ),
    ]
