# Generated by Django 2.0 on 2020-05-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_auto_20200522_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='parcelamento',
        ),
        migrations.AddField(
            model_name='receita',
            name='parcelado',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Parcelado'),
        ),
    ]
