# Generated by Django 2.0 on 2020-05-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_auto_20200505_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='processos.Cliente'),
            preserve_default=False,
        ),
    ]
