# Generated by Django 2.0 on 2020-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_auto_20200525_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='parcelado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parcelado'),
        ),
    ]
