# Generated by Django 2.0 on 2020-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_auto_20200507_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='Parcela',
        ),
    ]
