# Generated by Django 2.0 on 2020-05-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_remove_receita_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='Valor',
        ),
    ]
