# Generated by Django 2.0 on 2020-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_auto_20200505_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dataEntrega',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega'),
        ),
    ]
