# Generated by Django 2.0 on 2020-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_remove_receita_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balanco',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='Produto',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='produto',
        ),
        migrations.AlterField(
            model_name='despesas',
            name='despesa',
            field=models.CharField(choices=[('DOM', 'Domínio'), ('SN', 'Simples-Nacional'), ('HOSP', 'Hospedagem'), ('ISS', 'ISS'), ('MUL', 'Multa'), ('OUT', 'Outros')], max_length=4, verbose_name='Despesa'),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
