# Generated by Django 2.0 on 2020-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_auto_20200507_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receitas_id', models.IntegerField(blank=True, null=True, verbose_name='receitas_id')),
                ('despesa_id', models.IntegerField(blank=True, null=True, verbose_name='despesa_id')),
                ('receita', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='compra')),
                ('despesa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='despesa')),
                ('datas', models.DateField(blank=True, null=True, verbose_name='datas')),
            ],
            options={
                'verbose_name': 'Balanco',
                'verbose_name_plural': 'Balanco',
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
