# Generated by Django 2.0 on 2020-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_auto_20200505_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.IntegerField(choices=[(0, 'Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Resolvido')], max_length=4, verbose_name='Status'),
        ),
    ]
