# Generated by Django 2.0 on 2020-05-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_auto_20200507_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('Reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reuniao', to='processos.Reuniao')),
            ],
        ),
    ]
