# Generated by Django 2.0 on 2020-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_ata_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(upload_to='File', verbose_name='Arquivo'),
        ),
    ]
