# Generated by Django 2.0 on 2020-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_auto_20200505_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.IntegerField(choices=[(0, 'Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Resolvido')], verbose_name='Status'),
        ),
    ]
