# Generated by Django 2.0 on 2020-05-06 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_auto_20200506_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='ausencia',
            field=models.ManyToManyField(blank=True, null=True, related_name='ausencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='presenca',
            field=models.ManyToManyField(blank=True, null=True, related_name='presenca', to=settings.AUTH_USER_MODEL),
        ),
    ]
