# Generated by Django 2.0 on 2020-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_ata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='texto'),
        ),
    ]
