# Generated by Django 2.0 on 2020-05-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_auto_20200527_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(upload_to='documents/', verbose_name='Arquivo'),
        ),
    ]
