# Generated by Django 2.0 on 2020-05-08 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_auto_20200508_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
