# Generated by Django 2.0 on 2020-05-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_auto_20200506_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='descricaoReuniao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
