# Generated by Django 2.0 on 2020-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_auto_20200527_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(upload_to='', verbose_name='Arquivo'),
        ),
    ]
