# Generated by Django 2.0 on 2020-05-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_reuniao_descricaoreuniao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reuniao',
            old_name='datareuniao',
            new_name='dataReuniao',
        ),
    ]
