# Generated by Django 2.0 on 2020-05-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_auto_20200527_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ata',
            name='Arquivo',
        ),
    ]
