# Generated by Django 2.0 on 2020-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_auto_20200508_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='dataPublicacao',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
    ]
