# Generated by Django 2.0 on 2020-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0016_ata_datapublicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMembros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('Login', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('Situacao', models.BooleanField(default=True, verbose_name='Ativo')),
                ('CPF', models.CharField(max_length=20, verbose_name='CPF')),
                ('RG', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('Rua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('N', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('CEP', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('Facebook', models.CharField(blank=True, max_length=120, null=True, verbose_name='Facebook link')),
                ('Instagram', models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram link')),
                ('LinkedIn', models.CharField(blank=True, max_length=120, null=True, verbose_name='LinkedIn link')),
                ('Data_de_Nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('Data_de_Admissão', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('Data_de_Demissão', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('Funcao', models.CharField(choices=[('PROP', 'Proprietario'), ('PRE', 'Presidencia'), ('MAR', 'Marketing'), ('QUA', 'Qualidade'), ('ADM', 'Adm/Fin'), ('PRO', 'Projetos'), ('RH', 'Recursos Humanos')], max_length=4, verbose_name='Função')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='Bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
    ]
