# Generated by Django 2.0 on 2020-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0016_remove_ata_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(default=1, upload_to='', verbose_name='Arquivo'),
            preserve_default=False,
        ),
    ]
