# Generated by Django 2.0 on 2020-05-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0016_auto_20200506_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='dataReuniao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Reunião'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tipoReuniao',
            field=models.CharField(choices=[('GER', 'GERAL'), ('DIR', 'DIRETORIA')], max_length=4, verbose_name='Reunião'),
        ),
    ]
