# Generated by Django 2.0 on 2020-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0017_ata_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(default='', upload_to='', verbose_name='Arquivo'),
        ),
    ]
