# Generated by Django 2.0 on 2020-05-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0017_auto_20200509_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomembros',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
    ]
