# Generated by Django 2.0 on 2020-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0018_auto_20200509_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomembros',
            name='Membro_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Membro_id'),
        ),
    ]
