# Generated by Django 2.0 on 2020-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_auto_20200527_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(blank=True, default='', null=True, upload_to='Files', verbose_name='Arquivo'),
        ),
    ]
