# Generated by Django 2.0 on 2020-05-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_historicomembros_membro_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoMembros',
        ),
    ]
