# Generated by Django 2.0 on 2020-05-09 19:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_delete_historicomembros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvidoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
