# Generated by Django 2.0 on 2020-05-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_auto_20200527_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='Arquivo',
            field=models.FileField(default='', upload_to='Files', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(upload_to='profile', verbose_name='Foto'),
        ),
    ]
