# Generated by Django 2.0 on 2020-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_auto_20200527_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(upload_to="UploadTo('profile')", verbose_name='Foto'),
        ),
    ]
