# Generated by Django 2.0 on 2020-05-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0022_ouvidoria_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Matricula',
            field=models.CharField(default=1, max_length=128, verbose_name='Matricula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tipoReuniao',
            field=models.CharField(choices=[('GER', 'GERAL'), ('DIR', 'DIRETORIA'), ('PRO', 'PROJETOS')], max_length=4, verbose_name='Reunião'),
        ),
    ]
