# Generated by Django 2.0 on 2020-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_auto_20200513_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='Pagamento',
            field=models.BooleanField(default=True, verbose_name='Pagamento Efetuado'),
        ),
    ]
