# Generated by Django 2.0 on 2020-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_auto_20200527_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Foto'),
        ),
    ]
