# Generated by Django 2.0 on 2020-05-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0024_receita_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='parcelamento',
            field=models.CharField(choices=[(1, '01-A VISTA'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=1, max_length=4, verbose_name='Parcelado'),
            preserve_default=False,
        ),
    ]
