# Generated by Django 2.0 on 2020-05-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0025_servico_parcelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='parcelamento',
            field=models.IntegerField(choices=[(1, '01-A VISTA'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], max_length=4, verbose_name='Parcelado'),
        ),
    ]
