# Generated by Django 2.0 on 2020-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0026_auto_20200528_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(default=0, upload_to='profile', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
