# Generated by Django 2.0 on 2020-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0027_receita_parcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='Entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Entrada'),
            preserve_default=False,
        ),
    ]
