# Generated by Django 2.0 on 2020-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0028_receita_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='valorParcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor da Parcela'),
            preserve_default=False,
        ),
    ]
