# Generated by Django 2.0 on 2020-05-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0029_auto_20200529_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='texto',
            new_name='Email',
        ),
    ]
