# Generated by Django 2.0 on 2020-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0029_receita_valorparcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='Desconto',
        ),
        migrations.AddField(
            model_name='servico',
            name='Desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desconto'),
            preserve_default=False,
        ),
    ]
