# Generated by Django 2.0 on 2020-05-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0030_auto_20200529_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='membro',
            new_name='membros',
        ),
    ]
