# Generated by Django 2.0 on 2020-05-29 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0031_auto_20200529_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Aviso',
        ),
    ]
