# Generated by Django 2.0 on 2020-05-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0032_auto_20200529_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='Email',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='aviso',
            name='Data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='assunto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assunto'),
        ),
    ]
