# Generated by Django 2.0 on 2020-05-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0033_auto_20200529_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='membros',
        ),
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
