# Generated by Django 2.0 on 2020-05-30 02:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0034_auto_20200529_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('assunto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Assunto')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('membros', models.ManyToManyField(blank=True, null=True, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
