# Generated by Django 2.0 on 2020-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0035_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='tipoReuniao',
            field=models.CharField(choices=[('GER', 'GERAL'), ('DIR', 'DIRETORIA'), ('PRO', 'PROJETOS')], max_length=10, verbose_name='Reunião'),
        ),
    ]
