# Generated by Django 2.0 on 2020-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0036_auto_20200602_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='tipoReuniao',
            field=models.CharField(choices=[('GERAL', 'GERAL'), ('DIRETORIA', 'DIRETORIA'), ('PROJETOS', 'PROJETOS')], max_length=12, verbose_name='Reunião'),
        ),
    ]
