# Generated by Django 3.0.7 on 2020-06-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0037_auto_20200602_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='parcela',
            field=models.CharField(default=1, max_length=20, verbose_name='Parcela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Funcao',
            field=models.CharField(choices=[('PROP', 'Proprietario'), ('PRE', 'Presidencia'), ('MAR', 'Marketing'), ('QUA', 'Qualidade'), ('ADM', 'Adm/Financeiro'), ('PRO', 'Projetos'), ('RH', 'Recursos Humanos')], max_length=4, verbose_name='Função'),
        ),
    ]
