# Generated by Django 3.0.7 on 2020-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0038_auto_20200604_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
