# Generated by Django 3.0.7 on 2020-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0039_auto_20200606_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Data_de_Admissão',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Data_de_Demissão',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Data_de_Nascimento',
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tipoReuniao',
            field=models.CharField(choices=[('GERAL', 'GERAL'), ('DIRETORIA', 'DIRETORIA'), ('PROJETOS', 'PROJETOS'), ('EXTERNA', 'EXTERNA')], max_length=12, verbose_name='Reunião'),
        ),
    ]
