# Generated by Django 3.0.7 on 2020-06-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0040_auto_20200609_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Foto'),
        ),
    ]
