# Generated by Django 3.0.7 on 2020-07-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0041_auto_20200611_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='repositorio',
            field=models.URLField(default=0, max_length=128, verbose_name='Repositorio'),
            preserve_default=False,
        ),
    ]
