# Generated by Django 3.0.7 on 2020-07-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0042_projeto_repositorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanco',
            name='receita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='receita'),
        ),
    ]
