# Generated by Django 3.0.7 on 2020-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0043_auto_20200711_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
    ]
