# Generated by Django 3.0.7 on 2021-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0044_auto_20201009_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Bairro',
            field=models.CharField(default=0, max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CEP',
            field=models.CharField(default=0, max_length=50, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Funcao',
            field=models.CharField(choices=[('PROP', 'Proprietario'), ('PRE', 'Presidencia'), ('MAR', 'Marketing'), ('ADM', 'Adm/Financeiro'), ('PRO', 'Projetos'), ('RH', 'Recursos Humanos')], max_length=4, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='N',
            field=models.CharField(default=0, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='RG',
            field=models.CharField(default=0, max_length=20, verbose_name='RG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rua',
            field=models.CharField(default=0, max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
